---
builds:
- binary: faas-nomad
  goos:
  - linux
  goarch:
  - arm
  - arm64
  goarm:
  - 7
  env:
  - CGO_ENABLED=0

dockers:
-
  binary: faas-nomad
  goos: linux
  goarch: arm
  goarm: 7
  dockerfile: Dockerfile_arm7
  image_templates:
  - "jahentao/faas-nomad-provider:latest"
  - "jahentao/faas-nomad-provider:arm7-latest"
  - "jahentao/faas-nomad-provider:arm7-{{.Tag}}"
  - "jahentao/faas-nomad-provider:arm7-{{.Commit}}"
